/* data generated by https://json-generator.com/
    pictures from http://robohash.org/
*/

const people = [
    {
      "index": 0,
      "avatar": "http://robohash.org/BrittFlowers",
      "age": 22,
      "eyeColour": "brown",
      "name": "Glenn Kirby",
      "company": "EVEREST",
      "email": "glennkirby@everest.com",
      "phone": "+1 (824) 518-3531",
      "address": "517 Cedar Street, Hartsville/Hartley, Minnesota, 1067",
      "favouriteFruit": "strawberry"
    },
    {
      "index": 1,
      "avatar": "http://robohash.org/FrancoBryan",
      "age": 28,
      "eyeColour": "blue",
      "name": "Byers Malone",
      "company": "MEDCOM",
      "email": "byersmalone@medcom.com",
      "phone": "+1 (807) 525-3266",
      "address": "993 Royce Street, Homestead, South Dakota, 5276",
      "favouriteFruit": "strawberry"
    },
    {
      "index": 2,
      "avatar": "http://robohash.org/MagdalenaSloan",
      "age": 37,
      "eyeColour": "green",
      "name": "Ramos Barnett",
      "company": "INSURETY",
      "email": "ramosbarnett@insurety.com",
      "phone": "+1 (904) 462-2714",
      "address": "648 Mermaid Avenue, Wadsworth, Maryland, 1483",
      "favouriteFruit": "banana"
    },
    {
      "index": 3,
      "avatar": "http://robohash.org/MitziClay",
      "age": 38,
      "eyeColour": "brown",
      "name": "Teresa Hess",
      "company": "EXTRAGEN",
      "email": "teresahess@extragen.com",
      "phone": "+1 (822) 430-3050",
      "address": "922 Alton Place, Steinhatchee, Florida, 528",
      "favouriteFruit": "apple"
    },
    {
      "index": 4,
      "avatar": "http://robohash.org/GwenTucker",
      "age": 31,
      "eyeColour": "brown",
      "name": "Boyd Barker",
      "company": "ZENTIX",
      "email": "boydbarker@zentix.com",
      "phone": "+1 (969) 483-2219",
      "address": "115 Madison Street, Cutter, Michigan, 5801",
      "favouriteFruit": "strawberry"
    },
    {
      "index": 5,
      "avatar": "http://robohash.org/FieldsBrowning",
      "age": 22,
      "eyeColour": "green",
      "name": "Carissa Mcdonald",
      "company": "FLEXIGEN",
      "email": "carissamcdonald@flexigen.com",
      "phone": "+1 (956) 455-3742",
      "address": "808 Bridgewater Street, Frierson, District Of Columbia, 8552",
      "favouriteFruit": "strawberry"
    }
  ]

  